### ISSUE TITLE
Add support for MQTT 3.1.1 empty (zero length) client id

### ISSUE THREAD

**Issue by dhirajsb** [fusesource/mqtt-client#30]
To support the behavior required below, the clientId must be set to null in CONNECT.decode(), so that upstream code in ActiveMQ can then verify that cleanSession is also set, and respond with an nack if needed. 

From the draft MQTT 3.1.1 spec

[MQTT-3.1.3-6] A Server MAY allow a Client to supply a ClientId that has a length of zero bytes.
However if it does so the Server MUST treat this as a special case and assign a
unique ClientId to that Client. It MUST then process the CONNECT packet as if
the Client had provided that unique ClientId.
[MQTT-3.1.3-7] If the Client supplies a zero-byte ClientId, the Client MUST also set Clean
Session to 1.
[MQTT-3.1.3-8] If the Client supplies a zero-byte ClientId with Clean Session set to 0, the Server
MUST respond to the CONNECT Packet with a CONNACK return code 0x02
(Identifier rejected) and then close the Network Connection.
[MQTT-3.1.3-9] If the Server rejects the ClientId it MUST respond to the CONNECT Packet with
a CONNACK return code 0x02 (Identifier rejected) and then close the Network
Connection.

**Comment by dharminec** [comment]
What file contains this code?  I want to make some more changes to this. Can anyone suggest where does this code reside?

**Comment by dhirajsb** [comment]
Closing duplicate issue.
